### PR TITLE
changed to run on php-7.0

### PR DESCRIPTION
**Pull request by fgrosswig**
made some changes in Xmlrpc.php and Loader.php

### CODE REVIEW

**Comment by siniStar7boy** [comment]
@fgrosswig Have you tested this on your SWI instance and is everything working as it should?

**Comment by fgrosswig** [comment]
Yes …

Still finding failures on the code … which could be prevented …

You can check here: https://irc.king-arthur.eu/swi/index.php

Ill make a new pull later after fixing some other codes :)


Am 09.02.2017 um 22:47 schrieb Austin Ellis <notifications@github.com<mailto:notifications@github.com>>:


@fgrosswig<https://github.com/fgrosswig> Have you tested this on your SWI instance and is everything working as it should?

**Comment by fgrosswig** [comment]
ok this should be ok for integration

**Comment by siniStar7boy** [comment]
It seems to be working on that site without generating any PHP errors to me - though I may not have had sufficient access to see the errors.  Also, it looks like there are permission problems on the SWI index or directory to where /swi/ cannot be accessed without directly calling /swi/index.php - That could be either permissions or the nginx setup.  Looks good so far, thanks for investigating further and providing what looks like an acceptable fix for SWI users that want to use it on PHP 7.

**Pull request merged**
